### ISSUE TITLE
panic: runtime error with Go 1.7

### ISSUE THREAD

**Issue by BastienL** [snej/zdelta-go#1]
The package is not compatible with Go 1.7, probably because of the new cgo rules about sharing Go pointers with C code introduced in Go 1.6 (https://golang.org/doc/go1.6#cgo).
```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x40a7340, 0xc42000c300)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/snej/zdelta-go.zd_deflateInit(0xc42008a000, 0xffffffff, 0xc42004dda8)
	/Users/bastien/Code/go/src/github.com/snej/zdelta-go/zdelta_utils.go:24 +0x79
github.com/snej/zdelta-go.(*Compressor).WriteDelta(0xc42008a000, 0xc42000c2b8, 0x7, 0x8, 0xc42000c2f0, 0x9, 0x10, 0x41142e0, 0xc42001a0e0, 0x0, ...)
	/Users/bastien/Code/go/src/github.com/snej/zdelta-go/zdelta.go:127 +0xf9
github.com/snej/zdelta-go.(*Compressor).CreateDelta(0xc42008a000, 0xc42000c2b8, 0x7, 0x8, 0xc42000c2f0, 0x9, 0x10, 0x10, 0xc42000c2f0, 0xc42004de90, ...)
	/Users/bastien/Code/go/src/github.com/snej/zdelta-go/zdelta.go:156 +0xc6
github.com/snej/zdelta-go.CreateDelta(0xc42000c2b8, 0x7, 0x8, 0xc42000c2f0, 0x9, 0x10, 0x0, 0x4067d0d, 0x40a88c0, 0xc42000c2e0, ...)
	/Users/bastien/Code/go/src/github.com/snej/zdelta-go/zdelta.go:222 +0xb8
```
Do you have any idea @snej about how to fix this?

**Comment by snej** [comment]
Sorry, I haven't done any Go development in a couple of years (and this library was my only experience with CGo.)

I'm not currently using the library, but might in the near future, so if you find a fix it would be great if you could submit a pull request!

**Comment by BastienL** [comment]
@snej to be honest I'm afraid I run a bit out of time to work on this but I'll submit a PR for sure if I fix the issue.

**Comment by amlwwalker** [comment]
I don't suppose anyone got anywhere with this? I haven't found another delta library and I wondered if anyone had any suggestions

**Comment by snej** [comment]
Sorry! Haven't been using this library, but I'll definitely merge a PR if anyone updates it.
